name: Chuckle
favicon: null
layout_spectrum: 0.9533731623087078
typography_spectrum: 0.506
title: Never miss a mic again.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f98a9'
    - '#ec5d57'
    - '#e0c181'
    - '#4a4a4a'
  brandStrength: 0.875
  lightness: 0.9778266840148717
  saturation: 0.11160698439925909
  rhythmicContrast: 0.10238644131459296
purpose: []
