name: Chuckle
favicon: null
layout_spectrum: 0.9533731623087078
typography_spectrum: 0.9235832202248275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8871843772940338
  lightness: 0.9778266840148717
  saturation: 0.11160698439925909
  rhythmicContrast: 0.10238644131459296
purpose: []
